name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download and verify dependencies
      run: make deps
    
    - name: Run tests
      run: make test
    
    - name: Run linter
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.5.0
        args: --timeout=5m

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download and verify dependencies
      run: make deps
    
    - name: Build
      run: make build
    
    - name: Test binary
      run: ./bin/apkpure --help
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apkpure-go-ubuntu-latest-go1.25
        path: bin/apkpure
        retention-days: 7